<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_SellerSubAccount
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

if (empty($block->getRequest()->getParam('id'))) {
    $sellerId = $block->getRequest()->getParam('seller_id');
} else {
    $sellerId = $block->getSellerId();
}
?>
<input type="hidden" name="sub_account[seller_id]" 
value="<?=$block->escapeHtmlAttr($sellerId);?>" data-form-part="sellersubaccount_accounts_form"/>