<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_SellerSubAccount
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

$helper = $block->getLayout()->createBlock(
    \Webkul\SellerSubAccount\Block\SubAccount::class
)->_subAccHelper;

$isPartner = $block->getLayout()->createBlock(
    \Webkul\SellerSubAccount\Block\SubAccount::class
)->_mpHelper->isSeller();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$eavConfig = $objectManager->create(\Magento\Eav\Model\Config::class);
$attribute = $eavConfig->getAttribute('customer', 'gender');
$options = $attribute->getSource()->getAllOptions();
$dobMandatory = $helper->dobMandatory();
$genderMandatory = $helper->genderMandatory();

$tempblock = $block->getLayout()->createBlock(
    \Magento\Customer\Block\Form\Register::class
);
?>

<?php if ($isPartner == 1): ?>
    <?php
    $allPermissionTypes = $helper->getAllPermissionTypes();
    $id = (int)$block->getRequest()->getParam('id');
    if (!empty($id)) {
        $subAccountData = $helper->getSubAccountById($id);
        $allowedPermissions = explode(',', $subAccountData['permission_type']);
        $customerData = $helper->getCustomerById($subAccountData->getCustomerId());
        $firstname = $customerData->getFirstname();
        $lastname = $customerData->getLastname();
        $email = $customerData->getEmail();
        $customerDob = $customerData->getDob();
        $customerGender = $customerData->getGender();
        $status = $subAccountData->getStatus();
    } else {
        $allowedPermissions = [];
        $firstname = '';
        $lastname = '';
        $email = '';
        $status = 0;
        $customerDob='';
        $customerGender='';
    }
    /*
    *get permission allowed by admin
    */
    $getSellerPermissionForSubSellerByAdmin = $helper->getSellerPermissionForSubSellerByAdmin();
    ?>
    <input type="hidden" id="defaultdob" value="<?=$block->escapeHtmlAttr($customerDob); ?>"/>
    <input type="hidden" id="defaultgender" value="<?=$block->escapeHtmlAttr($customerGender); ?>">

    <form action="<?=$block->escapeUrl($block->getUrl('sellersubaccount/account/save')); ?>"
    enctype="multipart/form-data" method="post" id="form-sub-account" data-mage-init='{"validation":{}}'>
        <div class="fieldset wk-ui-component-container">
            <?= $block->getBlockHtml('formkey') ?>
            <?= $block->getBlockHtml('seller.formkey') ?>
            <input type="hidden" name="id" value="<?=$block->escapeHtmlAttr($id);?>"/>
            <div class="page-main-actions">
                <div class="page-actions-placeholder"></div>
                <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
                    <div class="page-actions-inner" data-title="<?=$block->escapeHtmlAttr(__("New Sub Account")); ?>">
                        <div class="page-actions-buttons">
                          <button id="back" title="<?=$block->escapeHtmlAttr(__("Back")); ?>"
                          type="button" class="action- scalable back" onclick="javascript: window.history.back();"
                          data-ui-id="back-button">
                              <span><?=$block->escapeHtml(__("Back")); ?></span>
                          </button>
                            <button id="reset" title="<?=$block->escapeHtmlAttr(__("Reset")); ?>"
                            type="reset" class="action- scalable reset" data-ui-id="reset-button" >
                                <span><?=$block->escapeHtml(__("Reset")); ?></span>
                            </button>
                            <button id="save" title="<?=$block->escapeHtmlAttr(__("Save Sub Account")); ?>"
                            type="submit" class="action- scalable save primary ui-button ui-widget
                            ui-state-default ui-corner-all ui-button-text-only"
                            data-form-role="save" data-ui-id="save-button"
                            role="button" aria-disabled="false">
                                <span class="ui-button-text">
                                    <span><?=$block->escapeHtml(__("Save Sub Account")); ?></span>
                                </span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="field required">
                <label for="firstname" class="label">
                    <span><?=$block->escapeHtml(__("First Name")); ?></span>
                </label>
                <div class="control">
                    <input type="text" class="input-text required-entry validate-no-html-tags" name="firstname"
                    data-validate="{required:true}" title="<?=$block->escapeHtmlAttr(__("First Name")); ?>"
                    id="firstname" value="<?=$block->escapeHtmlAttr($firstname) ?>">
                </div>
            </div>
            <div class="field required">
                <label for="lastname" class="label">
                    <span><?=$block->escapeHtml(__("Last Name")); ?></span>
                </label>
                <div class="control">
                    <input type="text" class="input-text required-entry validate-no-html-tags" name="lastname"
                    data-validate="{required:true}" title="<?=$block->escapeHtmlAttr(__("Last Name")); ?>"
                    id="lastname" value="<?=$block->escapeHtml($lastname) ?>">
                </div>
            </div>
            <?php if ($dobMandatory): ?>
                <div class="field required">
                    <label for="dob" class="label">
                        <span><?=$block->escapeHtml(__("Date Of Birth")); ?></span>
                    </label>
                    <div class="control">
                        <input type="text" class="input-text required-entry" id="dob" style="width: auto"
                        name="dob" data-validate="{required:true}" />
                    </div>
                </div>
            <?php endif ?>
            <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
            <?php if ($_gender->isEnabled() && $genderMandatory): ?>
                <?=$_gender->setGender($tempblock->getFormData()->getGender())->toHtml(); ?>
            <?php endif ?>
<script>
  require([
    'jquery',
    'mage/translate',
    'mage/calendar'
    ], function ($, $t) {
      $("#dob").val($("#defaultdob").val());
      $("#gender").val($("#defaultgender").val());
      $("#reset").on("click",function(e){ e.preventDefault();location.reload();});

      $('#dob').calendar({
        changeMonth: true,
        changeYear: true,
        showButtonPanel: true,
        currentText: $t('Go Today'),
        closeText: $t('Close'),
        showWeek: true,
        showsTime: false,
        dateFormat: "M/d/Y",
        yearRange: "-120y:c+nn",
        buttonText: "Select Date", maxDate: "-1d", changeMonth: true, changeYear: true, showOn: "both"

      });
    })


</script>

            <div class="field required">
                <label for="email" class="label">
                    <span><?=$block->escapeHtml(__("Email")); ?></span>
                </label>
                <div class="control">
                    <input type="text" class="input-text required-entry validate-email" name="email"
                    data-validate="{required:true}" title="<?=$block->escapeHtmlAttr(__("Email")); ?>"
                    id="email" value="<?=$block->escapeHtml($email) ?>">
                </div>
            </div>
            <div class="field required">
                <label for="permission_type" class="label">
                    <span><?=$block->escapeHtml(__("Allowed Permissions")); ?></span>
                </label>
                <?php if (($getSellerPermissionForSubSellerByAdmin[0])=="") {?>
                    <label for="permission_type" class="wk-label-for-permission">
                    <span><?=$block->escapeHtml(__("Admin didn't select any
                    permission to seller sub account")); ?></span>
                    </label>
                <?php } else { ?>
                <div class="control">
                    <select data-validate="{'validate-select':true}"
                    title="<?=$block->escapeHtmlAttr(__("Allowed Permissions")); ?>"
                    id="permission_type" name="permission_type[]"
                    class="required-entry select multiselect admin__control-multiselect"
                    size="<?=$block->escapeHtmlAttr(count($allPermissionTypes));?>" data-ui-id="select-permission-type"
                    multiple="multiple">
                        <?php
                        foreach ($allPermissionTypes as $value => $label):
                            foreach ($getSellerPermissionForSubSellerByAdmin as $value1):
                                if ($value == $value1):
                                    ?>
                                        <option value="<?=$block->escapeHtmlAttr($value); ?>"
                                        <?php if (in_array($value, $allowedPermissions)): ?>selected<?php endif; ?>>
                                        <?=$block->escapeHtml($label); ?></option>
                                    <?php
                                    endif;
                                endforeach;
                            endforeach;
                        ?>
                    </select>
                </div>
                <?php } ?>
            </div>
            <div class="field required">
                <label for="account_status" class="label">
                    <span><?=$block->escapeHtml(__("Active")); ?></span>
                </label>
                <div class="control">
                    <select data-validate="{'validate-select':true}" title="<?=$block->escapeHtmlAttr(__("Active"));
                    ?>" id="account_status" name="status" class="required-entry" data-ui-id="select-status">
                        <option value="1" <?php if ($status == 1): ?>selected<?php
                         endif; ?>><?=$block->escapeHtml(__('Yes')); ?></option>
                        <option value="0" <?php if ($status == 0): ?>selected<?php
                        endif; ?>><?=$block->escapeHtml(__('No')); ?></option>
                    </select>
                </div>
            </div>
        </div>
    </form>
    <div class="buttons-set">
        <p class="back-link">
            <a href="javascript:;" onclick="javascript: window.history.back();"
            class="left">&laquo; <?=$block->escapeHtml(__('Back'));?></a>
        </p>
    </div>
<?php else: ?>
    <h2 class="wk-mp-error-msg">
        <?=$block->escapeHtml(__("To Become Seller Please Contact to Admin.")); ?>
    </h2>
<?php endif; ?>
